# Config file for reconstructing objects from latent code

folder_sdf: '17_07_172540'   # Path containing training results, stored in results/runs_sdf, example: '14_05_2023'
obj_ids: '02942699/5d42d432ec71bfa1d5004b533b242ce6'   # Object ID to reconstruct from ShapeNetCore as category/instance, example: ['02942699/6d036fd1c70e5a5849493d905c02fa86'].
resolution: 256

# Visible bounding box for shape completion
x_axis_ratio_bbox: 1   # e.g. x_axis_ratio_bbox: 0.5, visible poincloud in half the object bounding box along the x-axis
y_axis_ratio_bbox: 0.5
z_axis_ratio_bbox: 1

# Inference parameters
epochs: 10000   # Number of epochs for latent code inference"
lr: 0.00001   # Learning rate for latent code inference
lr_scheduler: True   
lr_multiplier: 0.5   # Learning rate multiplier for the scheduler (if lr_scheduler: True)
patience: 100   # Patience for latent code inference (if lr_scheduler: True)
sigma_regulariser: 0.01   # Regulariser for the loss function
clamp: True   # Clip the network prediction
clamp_value: 0.1   # Clipping value